# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alhua/VivadoProject/RMSnorm/RMSnorm.srcs/sources_1/bd/RMSnormv2/ip/RMSnormv2_rms_norm_top_0_0/RMSnormv2_rms_norm_top_0_0.xci
# IP: The module: 'RMSnormv2_rms_norm_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/alhua/VivadoProject/RMSnorm/RMSnorm.srcs/sources_1/ip/bf_mul/bf_mul.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bf_mul || ORIG_REF_NAME==bf_mul} -quiet] -quiet

# IP: /home/alhua/VivadoProject/RMSnorm/RMSnorm.srcs/sources_1/ip/bf_sub/bf_sub.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bf_sub || ORIG_REF_NAME==bf_sub} -quiet] -quiet

# IP: /home/alhua/VivadoProject/RMSnorm/RMSnorm.srcs/sources_1/ip/bf_add/bf_add.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bf_add || ORIG_REF_NAME==bf_add} -quiet] -quiet

# IP: /home/alhua/VivadoProject/RMSnorm/RMSnorm.srcs/sources_1/ip/c_shift_ram_3/c_shift_ram_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_shift_ram_3 || ORIG_REF_NAME==c_shift_ram_3} -quiet] -quiet

# XDC: /home/alhua/VivadoProject/RMSnorm/RMSnorm.gen/sources_1/bd/RMSnormv2/ip/RMSnormv2_rms_norm_top_0_0/RMSnormv2_rms_norm_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RMSnormv2_rms_norm_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/alhua/VivadoProject/RMSnorm/RMSnorm.srcs/sources_1/bd/RMSnormv2/ip/RMSnormv2_rms_norm_top_0_0/RMSnormv2_rms_norm_top_0_0.xci
# IP: The module: 'RMSnormv2_rms_norm_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/alhua/VivadoProject/RMSnorm/RMSnorm.srcs/sources_1/ip/bf_mul/bf_mul.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bf_mul || ORIG_REF_NAME==bf_mul} -quiet] -quiet

# IP: /home/alhua/VivadoProject/RMSnorm/RMSnorm.srcs/sources_1/ip/bf_sub/bf_sub.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bf_sub || ORIG_REF_NAME==bf_sub} -quiet] -quiet

# IP: /home/alhua/VivadoProject/RMSnorm/RMSnorm.srcs/sources_1/ip/bf_add/bf_add.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bf_add || ORIG_REF_NAME==bf_add} -quiet] -quiet

# IP: /home/alhua/VivadoProject/RMSnorm/RMSnorm.srcs/sources_1/ip/c_shift_ram_3/c_shift_ram_3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_shift_ram_3 || ORIG_REF_NAME==c_shift_ram_3} -quiet] -quiet

# XDC: /home/alhua/VivadoProject/RMSnorm/RMSnorm.gen/sources_1/bd/RMSnormv2/ip/RMSnormv2_rms_norm_top_0_0/RMSnormv2_rms_norm_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'RMSnormv2_rms_norm_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
