# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alhua/VivadoProject/RMSnorm/RMSnorm.srcs/sources_1/ip/bf_sub/bf_sub.xci
# IP: The module: 'bf_sub' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alhua/VivadoProject/RMSnorm/MinimumSystem.gen/sources_1/ip/bf_sub/bf_sub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bf_sub'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/alhua/VivadoProject/RMSnorm/RMSnorm.srcs/sources_1/ip/bf_sub/bf_sub.xci
# IP: The module: 'bf_sub' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alhua/VivadoProject/RMSnorm/MinimumSystem.gen/sources_1/ip/bf_sub/bf_sub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bf_sub'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
