#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : compile.sh
# Simulator   : Siemens ModelSim Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Thu Oct 30 22:44:02 CST 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
bin_path="/home/anderson/intelFPGA/20.1/modelsim_ase/bin"
set -Eeuo pipefail
source matrix_tb_compile.do 2>&1 | tee compile.log

