######################################################################
#
# File name : matrix_tb_wave.do
# Created on: Thu Oct 30 21:41:42 CST 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
