######################################################################
#
# File name : RMS_top_tb_wave.do
# Created on: Thu Oct 30 22:09:23 CST 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
