######################################################################
#
# File name : RMS_top_tb_compile.do
# Created on: Thu Oct 30 22:33:38 CST 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlib modelsim_lib/work
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlib modelsim_lib/msim

/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlib modelsim_lib/msim/xbip_utils_v3_0_14
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlib modelsim_lib/msim/c_reg_fd_v12_0_10
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlib modelsim_lib/msim/c_shift_ram_v12_0_18
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlib modelsim_lib/msim/xil_defaultlib
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlib modelsim_lib/msim/axi_utils_v2_0_10
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlib modelsim_lib/msim/xbip_pipe_v3_0_10
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlib modelsim_lib/msim/xbip_dsp48_wrapper_v3_0_6
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlib modelsim_lib/msim/mult_gen_v12_0_22
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlib modelsim_lib/msim/floating_point_v7_1_19

/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vmap xbip_utils_v3_0_14 modelsim_lib/msim/xbip_utils_v3_0_14
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vmap c_reg_fd_v12_0_10 modelsim_lib/msim/c_reg_fd_v12_0_10
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vmap c_shift_ram_v12_0_18 modelsim_lib/msim/c_shift_ram_v12_0_18
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vmap axi_utils_v2_0_10 modelsim_lib/msim/axi_utils_v2_0_10
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vmap xbip_pipe_v3_0_10 modelsim_lib/msim/xbip_pipe_v3_0_10
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vmap xbip_dsp48_wrapper_v3_0_6 modelsim_lib/msim/xbip_dsp48_wrapper_v3_0_6
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vmap mult_gen_v12_0_22 modelsim_lib/msim/mult_gen_v12_0_22
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vmap floating_point_v7_1_19 modelsim_lib/msim/floating_point_v7_1_19

/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vcom -64 -93 -work xbip_utils_v3_0_14  \
"../../../../RMSnorm.ip_user_files/ipstatic/hdl/xbip_utils_v3_0_vh_rfs.vhd" \

/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vcom -64 -93 -work c_reg_fd_v12_0_10  \
"../../../../RMSnorm.ip_user_files/ipstatic/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \

/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vcom -64 -93 -work c_shift_ram_v12_0_18  \
"../../../../RMSnorm.ip_user_files/ipstatic/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \

/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vcom -64 -93 -work xil_defaultlib  \
"../../../../RMSnorm.gen/sources_1/ip/c_shift_ram_0/sim/c_shift_ram_0.vhd" \

/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vcom -64 -93 -work axi_utils_v2_0_10  \
"../../../../RMSnorm.ip_user_files/ipstatic/hdl/axi_utils_v2_0_vh_rfs.vhd" \

/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vcom -64 -93 -work xbip_pipe_v3_0_10  \
"../../../../RMSnorm.ip_user_files/ipstatic/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \

/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vcom -64 -93 -work xbip_dsp48_wrapper_v3_0_6  \
"../../../../RMSnorm.ip_user_files/ipstatic/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \

/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vcom -64 -93 -work mult_gen_v12_0_22  \
"../../../../RMSnorm.ip_user_files/ipstatic/hdl/mult_gen_v12_0_vh_rfs.vhd" \

/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vcom -64 -93 -work floating_point_v7_1_19  \
"../../../../RMSnorm.ip_user_files/ipstatic/hdl/floating_point_v7_1_rfs.vhd" \

/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlog -64 -incr -mfcu -work floating_point_v7_1_19  \
"../../../../RMSnorm.ip_user_files/ipstatic/hdl/floating_point_v7_1_rfs.v" \

/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlog -64 -incr -mfcu -work xil_defaultlib  \
"../../../../MinimumSystem.gen/sources_1/ip/bf_mul/sim/bf_mul.v" \
"../../../../Activation_accelerator.gen/sources_1/ip/floating_point_2/sim/floating_point_2.v" \
"../../../../Activation_accelerator.gen/sources_1/ip/floating_point_1/sim/floating_point_1.v" \
"../../../../RMSnorm.srcs/sources_1/new/add8.v" \
"../../../../RMSnorm.srcs/sources_1/new/gen_tlast.v" \
"../../../../RMSnorm.srcs/sources_1/new/parallel_squarev2.v" \
"../../../../RMSnorm.srcs/sources_1/new/squaresum_acc.v" \
"../../../../RMSnorm.srcs/sources_1/new/sum_align.v" \
"../../../../RMSnorm.srcs/sources_1/new/sum_keep.v" \
"../../../../RMSnorm.srcs/sources_1/new/rms_sum_topv2.v" \
"../../../../MinimumSystem.gen/sources_1/ip/bf_sub/sim/bf_sub.v" \
"../../../../RMSnorm.gen/sources_1/ip/bf_add/sim/bf_add.v" \

/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vcom -64 -93 -work xil_defaultlib  \
"../../../../MinimumSystem.gen/sources_1/ip/c_shift_ram_3/sim/c_shift_ram_3.vhd" \

/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlog -64 -incr -mfcu -work xil_defaultlib  \
"../../../../RMSnorm.srcs/sources_1/new/bf_fifo.v" \
"../../../../RMSnorm.srcs/sources_1/new/inv_fifo.v" \
"../../../../RMSnorm.srcs/sources_1/new/inv_sqrt.v" \
"../../../../RMSnorm.srcs/sources_1/new/inv_sqrt_top.v" \
"../../../../RMSnorm.srcs/sources_1/new/rms_norm_top.v" \
"../../../../RMSnorm.ip_user_files/bd/RMSnormv2/ip/RMSnormv2_rms_sum_topv2_0_0/sim/RMSnormv2_rms_sum_topv2_0_0.v" \
"../../../../RMSnorm.ip_user_files/bd/RMSnormv2/ip/RMSnormv2_rms_norm_top_0_0/sim/RMSnormv2_rms_norm_top_0_0.v" \
"../../../../RMSnorm.ip_user_files/bd/RMSnormv2/sim/RMSnormv2.v" \
"../../../../RMSnorm.gen/sources_1/bd/RMSnormv2/hdl/RMSnormv2_wrapper.v" \
"../../../../RMSnorm.srcs/sim_1/new/rms_top_tb.v" \

# compile glbl module
/home/anderson/intelFPGA/20.1/modelsim_ase/bin/vlog -work xil_defaultlib "glbl.v"

