#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Siemens ModelSim Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Oct 30 22:44:08 CST 2025
# SW Build 5239630 on Fri Nov 08 22:34:34 MST 2024
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
bin_path="/home/anderson/intelFPGA/20.1/modelsim_ase/bin"
set -Eeuo pipefail
$bin_path/vsim -64  -do "do {matrix_tb_simulate.do}" -l simulate.log

