# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/RMSnorm/RMSnorm.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RMSnorm || ORIG_REF_NAME==RMSnorm} -quiet] -quiet

# IP: bd/RMSnorm/ip/RMSnorm_rms_sum_top_0_0/RMSnorm_rms_sum_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RMSnorm_rms_sum_top_0_0 || ORIG_REF_NAME==RMSnorm_rms_sum_top_0_0} -quiet] -quiet

# IP: ip/c_shift_ram_2/c_shift_ram_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_shift_ram_2 || ORIG_REF_NAME==c_shift_ram_2} -quiet] -quiet

# IP: ip/floating_point_2/floating_point_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_2 || ORIG_REF_NAME==floating_point_2} -quiet] -quiet

# IP: ip/floating_point_1/floating_point_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_1 || ORIG_REF_NAME==floating_point_1} -quiet] -quiet

# IP: ip/c_shift_ram_1/c_shift_ram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_shift_ram_1 || ORIG_REF_NAME==c_shift_ram_1} -quiet] -quiet

# IP: ip/bf_mul/bf_mul.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bf_mul || ORIG_REF_NAME==bf_mul} -quiet] -quiet

# IP: bd/RMSnorm/ip/RMSnorm_rms_norm_top_0_0/RMSnorm_rms_norm_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RMSnorm_rms_norm_top_0_0 || ORIG_REF_NAME==RMSnorm_rms_norm_top_0_0} -quiet] -quiet

# IP: ip/bf_mul/bf_mul.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bf_mul || ORIG_REF_NAME==bf_mul} -quiet] -quiet

# IP: ip/bf_sub/bf_sub.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bf_sub || ORIG_REF_NAME==bf_sub} -quiet] -quiet

# IP: ip/c_shift_ram_3/c_shift_ram_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==c_shift_ram_3 || ORIG_REF_NAME==c_shift_ram_3} -quiet] -quiet

# XDC: /home/alhua/VivadoProject/RMSnorm/RMSnorm.gen/sources_1/bd/RMSnorm/RMSnorm_ooc.xdc
